### ISSUE TITLE
Test all available geometry sources

### ISSUE THREAD

**Issue by rafaqz** [JuliaGeo/GeometryOps.jl#134]
We should automate testing across geometry types from:

ArchGDAL.jl
LibGEOS.jl
GeoInterface.jl
GeometryBasics.jl
Meshes.jl

Just using `GI.convert` in a loop over the modules.

And maybe Shapefile,jl and GeoJSON.jl ? These would need write/read to convert, as there is no `GI.convert` for them as its not very useful except for testing like this.

This would make use of GeometryOps.jl much more robust, avoiding errors like #133 

It would also provide some useful tests on the rest of the ecosystems GeoInterface implementations.

**Comment by asinghvi17** [comment]
https://github.com/JuliaGeo/GeometryOps.jl/blob/main/benchmarks/geometry_providers.jl was meant to benchmark them but it ended up examining only the performance of Shapefile.jl. 

It would work as a good base to run the rest, though...

**Comment by rafaqz** [comment]
I wrote a macro to wrap all our tests in:
```julia
using GeoInterface, ArchGDAL, GeometryBasics, LibGEOS

macro test_all_implementations(args, code)
    args = esc(args)
    quote
        for mod in (GeoInterface, ArchGDAL, GeometryBasics, LibGEOS)
            let ($args = map(g -> GeoInterface.convert(mod, g), $args))
                $code
            end
        end
    end
end

pointa = (1, 2)
pointb = (3, 4)
@test_all_implementations (pointa, pointb) begin 
    # tests here
end
```
