### ISSUE TITLE
rename linear manifold to Euclidean?

### ISSUE THREAD

**Issue by tiemvanderdeure** [JuliaGeo/GeometryOps.jl#222]
I'm not a mathematician and a little out of my depth here, but the name `Linear` seems unintuitive to me for calculations in Euclidean space. Why don't we call it `Euclidean`?  Linear sounds kind of 1D. If we want to specify that it is 2D space we could call it `Planar`, but I don't think that we do?

https://github.com/JuliaGeo/GeometryOps.jl/blob/737340f599d7066a57fde2fc33fd9d7ee98ccb91/GeometryOpsCore/src/types.jl#L38-L45

Manifolds.jl also calls their manifold in euclidean space `Euclidean`: https://juliamanifolds.github.io/Manifolds.jl/latest/manifolds/euclidean.html

**Comment by rafaqz** [comment]
I was also confused about what `Linear` meant, +1 for `Euclidian`

**Comment by asinghvi17** [comment]
I would be fine with either Planar or Euclidean, but I feel like Planar is a bit more descriptive about what is actually going on?

**Comment by rafaqz** [comment]
I guess those methods will always be 2d?

**Comment by asinghvi17** [comment]
Most likely, if we go into 3d we can always deprecated Planar for Euclidean
